CREATE TABLE `uploaded_documents` (
	`id` int AUTO_INCREMENT NOT NULL,
	`dealId` varchar(64) NOT NULL,
	`filename` varchar(512) NOT NULL,
	`originalName` varchar(512) NOT NULL,
	`mimeType` varchar(128) NOT NULL,
	`fileSize` int NOT NULL,
	`s3Key` varchar(1024) NOT NULL,
	`s3Url` text NOT NULL,
	`classifiedType` varchar(128),
	`classificationConfidence` float,
	`classificationStatus` enum('pending','processing','completed','failed') NOT NULL DEFAULT 'pending',
	`extractedFields` json,
	`aiSummary` text,
	`requiresHumanReview` boolean NOT NULL DEFAULT false,
	`reviewReason` text,
	`reviewStatus` enum('pending','approved','rejected','flagged') NOT NULL DEFAULT 'pending',
	`reviewedBy` varchar(128),
	`reviewNote` text,
	`uploadedAt` timestamp NOT NULL DEFAULT (now()),
	`classifiedAt` timestamp,
	`reviewedAt` timestamp,
	CONSTRAINT `uploaded_documents_id` PRIMARY KEY(`id`)
);
